W0315 03:23:00.746388   29694 pod_container_deletor.go:77] Container "f12e1887d044191480200b7e10293708d50caebd8b06a9777937d8e55a5cd03c" not found in pod's containers
I0315 03:23:00.748299   29694 kuberuntime_manager.go:383] No ready sandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" can be found. Need to start a new one
I0315 03:23:00.748415   29694 kuberuntime_manager.go:457] Container {Name:pylon Image:192.168.6.23:5000/iecas/pylon:v1.1 Command:[] Args:[] WorkingDir: Ports:[{Name:pylon HostPort:80 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:REST_SERVER_URI Value:http://192.168.6.23:9186 ValueFrom:nil} {Name:K8S_API_SERVER_URI Value:http://192.168.6.23:8080 ValueFrom:nil} {Name:WEBHDFS_URI Value:http://192.168.6.23:50070 ValueFrom:nil} {Name:PROMETHEUS_URI Value:http://192.168.6.23:9091 ValueFrom:nil} {Name:K8S_DASHBOARD_URI Value:http://192.168.6.23:9090 ValueFrom:nil} {Name:GRAFANA_URI Value:http://192.168.6.23:3000 ValueFrom:nil} {Name:WEBPORTAL_URI Value:http://192.168.6.23:9286 ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
E0315 03:23:01.069163   29694 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_74 (5431d33e09b4b6ad7c9de90572fed3370439a360de3b97f3c961a18447696c82): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:01.069234   29694 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_74 (5431d33e09b4b6ad7c9de90572fed3370439a360de3b97f3c961a18447696c82): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:01.069264   29694 kuberuntime_manager.go:618] createPodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_74 (5431d33e09b4b6ad7c9de90572fed3370439a360de3b97f3c961a18447696c82): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:01.069323   29694 pod_workers.go:182] Error syncing pod fa0abbee-27ff-11e8-b984-ac1f6b26d506 ("pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)"), skipping: failed to "CreatePodSandbox" for "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" with CreatePodSandboxError: "CreatePodSandbox for pod \"pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)\" failed: rpc error: code = 2 desc = failed to start sandbox container for pod \"pylon-ds-kdtwf\": Error response from daemon: {\"message\":\"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_74 (5431d33e09b4b6ad7c9de90572fed3370439a360de3b97f3c961a18447696c82): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use\"}"
I0315 03:23:01.784041   29694 kubelet.go:1912] SyncLoop (PLEG): "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)", event: &pleg.PodLifecycleEvent{ID:"fa0abbee-27ff-11e8-b984-ac1f6b26d506", Type:"ContainerDied", Data:"cb736e883694bb0714f16ac07e4959302edb9065c5427321b5de08ae02fdde62"}
W0315 03:23:01.784121   29694 pod_container_deletor.go:77] Container "cb736e883694bb0714f16ac07e4959302edb9065c5427321b5de08ae02fdde62" not found in pod's containers
I0315 03:23:01.786050   29694 kuberuntime_manager.go:383] No ready sandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" can be found. Need to start a new one
I0315 03:23:01.786142   29694 kuberuntime_manager.go:457] Container {Name:pylon Image:192.168.6.23:5000/iecas/pylon:v1.1 Command:[] Args:[] WorkingDir: Ports:[{Name:pylon HostPort:80 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:REST_SERVER_URI Value:http://192.168.6.23:9186 ValueFrom:nil} {Name:K8S_API_SERVER_URI Value:http://192.168.6.23:8080 ValueFrom:nil} {Name:WEBHDFS_URI Value:http://192.168.6.23:50070 ValueFrom:nil} {Name:PROMETHEUS_URI Value:http://192.168.6.23:9091 ValueFrom:nil} {Name:K8S_DASHBOARD_URI Value:http://192.168.6.23:9090 ValueFrom:nil} {Name:GRAFANA_URI Value:http://192.168.6.23:3000 ValueFrom:nil} {Name:WEBPORTAL_URI Value:http://192.168.6.23:9286 ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
E0315 03:23:02.105443   29694 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_75 (ceaae0d4b4c33b51b099b7235323277f67bfedd1f3b6df33799510df5470a3c3): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:02.105538   29694 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_75 (ceaae0d4b4c33b51b099b7235323277f67bfedd1f3b6df33799510df5470a3c3): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:02.105567   29694 kuberuntime_manager.go:618] createPodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_75 (ceaae0d4b4c33b51b099b7235323277f67bfedd1f3b6df33799510df5470a3c3): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:02.105630   29694 pod_workers.go:182] Error syncing pod fa0abbee-27ff-11e8-b984-ac1f6b26d506 ("pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)"), skipping: failed to "CreatePodSandbox" for "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" with CreatePodSandboxError: "CreatePodSandbox for pod \"pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)\" failed: rpc error: code = 2 desc = failed to start sandbox container for pod \"pylon-ds-kdtwf\": Error response from daemon: {\"message\":\"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_75 (ceaae0d4b4c33b51b099b7235323277f67bfedd1f3b6df33799510df5470a3c3): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use\"}"
I0315 03:23:02.831613   29694 kubelet.go:1912] SyncLoop (PLEG): "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)", event: &pleg.PodLifecycleEvent{ID:"fa0abbee-27ff-11e8-b984-ac1f6b26d506", Type:"ContainerDied", Data:"52cc2188f384ec1c0d7d8cc46be16746dde95c13fd11fe1013ce6498940be651"}
W0315 03:23:02.831674   29694 pod_container_deletor.go:77] Container "52cc2188f384ec1c0d7d8cc46be16746dde95c13fd11fe1013ce6498940be651" not found in pod's containers
I0315 03:23:02.833506   29694 kuberuntime_manager.go:383] No ready sandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" can be found. Need to start a new one
I0315 03:23:02.833603   29694 kuberuntime_manager.go:457] Container {Name:pylon Image:192.168.6.23:5000/iecas/pylon:v1.1 Command:[] Args:[] WorkingDir: Ports:[{Name:pylon HostPort:80 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:REST_SERVER_URI Value:http://192.168.6.23:9186 ValueFrom:nil} {Name:K8S_API_SERVER_URI Value:http://192.168.6.23:8080 ValueFrom:nil} {Name:WEBHDFS_URI Value:http://192.168.6.23:50070 ValueFrom:nil} {Name:PROMETHEUS_URI Value:http://192.168.6.23:9091 ValueFrom:nil} {Name:K8S_DASHBOARD_URI Value:http://192.168.6.23:9090 ValueFrom:nil} {Name:GRAFANA_URI Value:http://192.168.6.23:3000 ValueFrom:nil} {Name:WEBPORTAL_URI Value:http://192.168.6.23:9286 ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
E0315 03:23:03.117104   29694 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_76 (8fc3cfdda0cb8a6684964a3e99a6b28f7383d01a9bb4e87bf7c4f972f552ca7b): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:03.117190   29694 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_76 (8fc3cfdda0cb8a6684964a3e99a6b28f7383d01a9bb4e87bf7c4f972f552ca7b): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:03.117224   29694 kuberuntime_manager.go:618] createPodSandbox for pod "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "pylon-ds-kdtwf": Error response from daemon: {"message":"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_76 (8fc3cfdda0cb8a6684964a3e99a6b28f7383d01a9bb4e87bf7c4f972f552ca7b): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use"}
E0315 03:23:03.117289   29694 pod_workers.go:182] Error syncing pod fa0abbee-27ff-11e8-b984-ac1f6b26d506 ("pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)"), skipping: failed to "CreatePodSandbox" for "pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)" with CreatePodSandboxError: "CreatePodSandbox for pod \"pylon-ds-kdtwf_default(fa0abbee-27ff-11e8-b984-ac1f6b26d506)\" failed: rpc error: code = 2 desc = failed to start sandbox container for pod \"pylon-ds-kdtwf\": Error response from daemon: {\"message\":\"driver failed programming external connectivity on endpoint k8s_POD_pylon-ds-kdtwf_default_fa0abbee-27ff-11e8-b984-ac1f6b26d506_76 (8fc3cfdda0cb8a6684964a3e99a6b28f7383d01a9bb4e87bf7c4f972f552ca7b): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use\"}"
